version: '3'

services:
  php:
    build: php/7.3
    working_dir: /var/www/laravel
    depends_on:
      - db
      - redis
    volumes:
      - ./laravel:/var/www/laravel
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  horizon:
    build: php/7.3
    working_dir: /var/www/laravel
    command: php artisan horizon
    depends_on:
      - db
    volumes:
      - ./laravel:/var/www/laravel
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  db:
    image: mariadb:10.4
    command: --default-authentication-plugin=mysql_native_password
    # ports:
    # - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
    volumes:
      - ./data/db:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8200:80"
    environment:
      - PMA_HOST=db
      # To enable host input field
      # - PMA_ARBITRARY=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./laravel:/var/www/laravel
    depends_on:
      - php
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  redis:
    image: redis:alpine
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
